import { TikTokOperationDescriptor } from "@/lib/integrations/tiktok/types";

export const tiktokOperationCatalog: TikTokOperationDescriptor[] = [
  {
    id: "auth.advertisers.list",
    method: "GET",
    path: "/open_api/v1.3/oauth2/advertiser/get/",
    description: "Lista advertisers autorizados pela app.",
    group: "auth",
    needsAccessToken: true,
  },
  {
    id: "bc.list",
    method: "GET",
    path: "/open_api/v1.3/bc/get/",
    description: "Lista Business Centers acessiveis.",
    group: "bc",
    needsAccessToken: true,
  },
  {
    id: "bc.members.list",
    method: "GET",
    path: "/open_api/v1.3/bc/member/get/",
    description: "Lista membros de um BC.",
    group: "bc",
    needsAccessToken: true,
  },
  {
    id: "bc.partners.list",
    method: "GET",
    path: "/open_api/v1.3/bc/partner/get/",
    description: "Lista parceiros do BC.",
    group: "bc",
    needsAccessToken: true,
  },
  {
    id: "bc.assets.list",
    method: "GET",
    path: "/open_api/v1.3/bc/asset/get/",
    description: "Lista assets vinculados ao BC.",
    group: "bc",
    needsAccessToken: true,
  },
  {
    id: "bc.advertiser.create",
    method: "POST",
    path: "/open_api/v1.3/bc/advertiser/create/",
    description: "Cria advertiser em Business Center.",
    group: "bc",
    needsAccessToken: true,
  },
  {
    id: "pixel.list",
    method: "GET",
    path: "/open_api/v1.3/pixel/list/",
    description: "Lista pixels por advertiser.",
    group: "pixels",
    needsAccessToken: true,
  },
  {
    id: "pixel.create",
    method: "POST",
    path: "/open_api/v1.3/pixel/create/",
    description: "Cria pixel.",
    group: "pixels",
    needsAccessToken: true,
  },
  {
    id: "pixel.update",
    method: "POST",
    path: "/open_api/v1.3/pixel/update/",
    description: "Atualiza pixel.",
    group: "pixels",
    needsAccessToken: true,
  },
  {
    id: "pixel.link.update",
    method: "POST",
    path: "/open_api/v1.3/bc/pixel/link/update/",
    description: "Link/unlink de pixel para advertisers.",
    group: "pixels",
    needsAccessToken: true,
  },
  {
    id: "pixel.transfer",
    method: "POST",
    path: "/open_api/v1.3/bc/pixel/transfer/",
    description: "Transfere pixel entre advertiser e BC.",
    group: "pixels",
    needsAccessToken: true,
  },
  {
    id: "asset.image.upload",
    method: "POST",
    path: "/open_api/v1.3/file/image/ad/upload/",
    description: "Upload de imagem para ad asset library.",
    group: "assets",
    needsAccessToken: true,
  },
  {
    id: "asset.video.upload",
    method: "POST",
    path: "/open_api/v1.3/file/video/ad/upload/",
    description: "Upload de video para ad asset library.",
    group: "assets",
    needsAccessToken: true,
  },
  {
    id: "campaign.list",
    method: "GET",
    path: "/open_api/v1.3/campaign/get/",
    description: "Lista campanhas.",
    group: "campaigns",
    needsAccessToken: true,
  },
  {
    id: "campaign.create",
    method: "POST",
    path: "/open_api/v1.3/campaign/create/",
    description: "Cria campanha.",
    group: "campaigns",
    needsAccessToken: true,
  },
  {
    id: "campaign.update",
    method: "POST",
    path: "/open_api/v1.3/campaign/update/",
    description: "Atualiza campanha.",
    group: "campaigns",
    needsAccessToken: true,
  },
  {
    id: "campaign.status.update",
    method: "POST",
    path: "/open_api/v1.3/campaign/status/update/",
    description: "Atualiza status da campanha.",
    group: "campaigns",
    needsAccessToken: true,
  },
  {
    id: "adgroup.list",
    method: "GET",
    path: "/open_api/v1.3/adgroup/get/",
    description: "Lista adgroups.",
    group: "adgroups",
    needsAccessToken: true,
  },
  {
    id: "adgroup.create",
    method: "POST",
    path: "/open_api/v1.3/adgroup/create/",
    description: "Cria adgroup.",
    group: "adgroups",
    needsAccessToken: true,
  },
  {
    id: "adgroup.update",
    method: "POST",
    path: "/open_api/v1.3/adgroup/update/",
    description: "Atualiza adgroup.",
    group: "adgroups",
    needsAccessToken: true,
  },
  {
    id: "adgroup.status.update",
    method: "POST",
    path: "/open_api/v1.3/adgroup/status/update/",
    description: "Atualiza status do adgroup.",
    group: "adgroups",
    needsAccessToken: true,
  },
  {
    id: "ad.list",
    method: "GET",
    path: "/open_api/v1.3/ad/get/",
    description: "Lista ads.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "ad.create",
    method: "POST",
    path: "/open_api/v1.3/ad/create/",
    description: "Cria ad.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "ad.update",
    method: "POST",
    path: "/open_api/v1.3/ad/update/",
    description: "Atualiza ad.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "ad.status.update",
    method: "POST",
    path: "/open_api/v1.3/ad/status/update/",
    description: "Atualiza status do ad.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "smartplus.ad.appeal",
    method: "POST",
    path: "/open_api/v1.3/smart_plus/ad/appeal/",
    description: "Envia appeal de ad Smart Plus.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "smartplus.ad.review.info",
    method: "GET",
    path: "/open_api/v1.3/smart_plus/ad/review_info/",
    description: "Consulta review info de ads Smart Plus.",
    group: "ads",
    needsAccessToken: true,
  },
  {
    id: "smartplus.material.review.info",
    method: "GET",
    path: "/open_api/v1.3/smart_plus/material/review_info/",
    description: "Consulta review info de criativos Smart Plus.",
    group: "ads",
    needsAccessToken: true,
  },
];

export function findTikTokOperation(operationId: string) {
  return tiktokOperationCatalog.find((item) => item.id === operationId) ?? null;
}
